### ISSUE TITLE
Outdated version (9.13.2 vs 10.1.3)

### ISSUE THREAD

**Issue by JuanCDe** [polkadot-js/dotapps.io#17]
Outdated version:
The current hosted Polkadot-JS UI API version is `v10.1.3`
The current IPFS API version is `v9.13.2`

UI:
Teleporting button is available on the IPFS version

**Comment by jacogr** [comment]
The IPFS version only gets updated on an actual [apps UI release](https://github.com/polkadot-js/apps/releases). Sadly these have not come in at the frequency we would expect lately.

To compound matters further, we also had some [IPFS publishing issues](https://github.com/polkadot-js/apps/issues/9279) due to the PinataSDK, which didn't help matters at all.

As of this morning however (with an actual release & downgrade of pinning libs), IPFS is once again on [latest](https://github.com/polkadot-js/apps/releases/tag/v0.126.1).
